### ISSUE TITLE
Create Branches

### ISSUE THREAD

**Issue by cr4zym4n** [cr4zym4n/ProiectPOS#1]
Create Branches for review and proper integration purposes.
Find out how to use a review system.

**Comment by cr4zym4n** [comment]
To do a branch, you should use the following:
git checkout -b <branch_name>
After this, you make the required modifications, and then:
you add and commit them as usual. After that, when you need to push, you write
git push origin, and the push message you need to use will be displated on screen.
Use that message:
git push --set-upstream origin <branch_name>

**Comment by DreamEvil88** [comment]
Done!
