### ISSUE TITLE
Create 3 layer arhitecture

### ISSUE THREAD

**Issue by cr4zym4n** [cr4zym4n/ProiectPOS#6]

**Comment by cr4zym4n** [comment]
We need to create 2 servers. One that connects to the client, and handles requests accordingly, by processing them and answering , or sending them further to the next server, in the Data access layer. Also this first server will handle switching between it and the game server. 
The second server will handle database querries and send back to the business logic layer to be then sent again to the client.

**Comment by cr4zym4n** [comment]
Successfully created the business logic layer. It implements the HTTP protocol, and communicates with the client. It contains the following HTTP methods : GET, POST, PUT, DELETE.

**Comment by cr4zym4n** [comment]
Done! Check "3 way server comm" Commit

**Comment by DreamEvil88** [comment]
index.html almost done! In this moment it is a template :D
